name: Release

on:
  workflow_dispatch:   # Déclenchement manuel via GitHub Actions
  push:
    branches:
      - main

jobs:
  release:
    name: Release via release.sh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "auth OK"

      - name: Run release.sh with standard-version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash release.sh standard-version
